engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR2"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,cleancode,design,codesize"
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "lib/SmartBot/**.php"
exclude_paths:
  - "tests/**"
  - "vendor/**"
  - "*.yml"
  - "*.md"