engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "Zend"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,cleancode,design,codesize"
      exclude: "tests/*,vendor/*"
ratings:
  paths:
  - "lib/SmartBot/**.php"