sudo: false

language: php

php:
  - 5.5

script:
  - composer self-update
  - composer install
#  - phpunit -d date.timezone=Australia/Sydney tests/AllTests.php
#  - php ./vendor/bin/phpcs ./lib/SmartBot --standard=PHPCS --report=summary -np
  - php ./vendor/bin/phpcs --report-summary -np --standard=Zend ./lib/SmartBot/

