sudo: false

language: php

php:
  - 5.5

script:
  - composer self-update
  - composer install
  - phpunit -d date.timezone=Europe/Paris --configuration ./phpunit.xml
  - php ./vendor/bin/phpcs -np --standard=Zend ./lib/SmartBot/ > phpcs.log
  - php ./vendor/bin/phpcs --report-summary -np --standard=Zend ./lib/SmartBot/

